// This test creates 2 UDP SIP endpoints, makes a call between them and disconeects.

const sip = require ('../index.js')
const Zeq = require('@mayama/zeq')
const m = require('data-matching')
const sip_msg = require('sip-matching')

const crypto = require('crypto');

function generateDigestResponse({
    username, password, realm, nonce, uri,
    method = 'INVITE', qop = 'auth', nc = '00000001',
    cnonce 
}) {
    const md5 = (str) => crypto.createHash('md5').update(str).digest('hex');

    // Fallback to random ONLY if one isn't provided (for tests)
    const finalCnonce = cnonce || crypto.randomBytes(8).toString('hex');

    const ha1 = md5(`${username}:${realm}:${password}`);
    const ha2 = md5(`${method}:${uri}`);
    const response = md5(`${ha1}:${nonce}:${nc}:${finalCnonce}:${qop}:${ha2}`);

    return { response, cnonce: finalCnonce };
}

// here we create our Zeq instance
var z = new Zeq()


async function test() {
    // here we set DTMF aggregation mode to 500 ms
    sip.dtmf_aggregation_on(500)

    // here we set our Zeq instance to trap events generated by sip-lab event_source
    z.trap_events(sip.event_source, 'event', (evt) => {
        var e = evt.args[0]
        return e
    })

    sip.set_codecs("pcmu/8000/1:128,pcma/8000/1:128,gsm/8000/1:128")

    // here we start sip-lab
    console.log(await sip.start((data) => { console.log(data)} ))

    // Here we create the SIP endpoints (transports).
    // Since we don't specify the port, an available port will be allocated.
    // Since we don't specify the type ('udp' or 'tcp' or 'tls'), 'udp' will be used by default.
    const t1 = await sip.transport.create({address: "127.0.0.1"})
    const t2 = await sip.transport.create({address: "127.0.0.1"})

    // here we just print the transports
    console.log("t1", t1)
    console.log("t2", t2)

    max_forwards = '18'

    var username = 'alice'
    var password = 'secret'
    var realm = 'test.com'

    // make the call from t1 to t2 with some custom heaaders
    const oc = await sip.call.create(t1.id, {
        from_uri: 'sip:alice@test.com',
        to_uri: `sip:bob@${t2.address}:${t2.port}`,
        auth: {
            username,
            password,
            realm,
        },
    })

    // Here we will wait for the call to arrive at t2
    // We will also get a '100 Trying' that is sent by sip-lab automatically
    // We will wait for at most 1000ms. If all events don't arrive within 1000ms, an exception will be thrown and the test will fail due to timeout.
    await z.wait([
        {
            event: "incoming_call",
            call_id: m.collect("call_id"),
            transport_id: t2.id,
            msg: sip_msg({
                $rU: 'bob',
                $fU: 'alice',
                $tU: 'bob',
                $fd: 'test.com',
                $ru: m.collect('ruri'),
                hds_call_id: m.collect('sip_call_id'),
            })
        },
        {
            event: 'response',
            call_id: oc.id,
            method: 'INVITE',
            msg: sip_msg({
                $rs: '100',
                $rr: 'Trying',
            }),
        },
    ], 1000)

    // Here we store data for the incoming call
    // just to organize our code (not really needed)
    var ic = {
        id: z.$call_id,
        sip_call_id: z.$sip_call_id,
    }

    // Now we challenge the caller.
    var nonce = "dcd98b7102dd2f0e8b11d0f600bfb0c093"
    var qop = 'auth'
    var algorithm = 'MD5'
    var uri = z.$ruri
    await sip.call.respond(ic.id, {
        code: 407,
        reason: 'Proxy Authentication Required',
        headers: {
            'Proxy-Authenticate': `Digest realm="${realm}", nonce="${nonce}", algorithm=${algorithm}, qop="${qop}"`,
        },
    })

    // the caller gets the challenge and the call ends at t2.
    await z.wait([
        {
            event: 'response',
            call_id: oc.id,
            method: 'INVITE',
            msg: sip_msg({
                $rs: '407',
                $rr: 'Proxy Authentication Required',
                hdr_proxy_authenticate: `Digest realm="${realm}",nonce="${nonce}",algorithm=${algorithm},qop="${qop}"`,
            }),
        },
        {
            event: 'call_ended',
            call_id: ic.id,
        }
    ], 1000)

    z.store.call_id = null
    z.store.sip_call_id = null
 
    // Then we wait for INVITE with header Authorization
    await z.wait([
        {
            event: "incoming_call",
            call_id: m.collect("call_id"),
            transport_id: t2.id,
            msg: sip_msg({
                $rU: 'bob',
                $fU: 'alice',
                $tU: 'bob',
                $fd: 'test.com',
                hdr_proxy_authorization: 'Digest username="!{username}", realm="!{realm}", nonce="!{nonce}", uri="!{uri}", response="!{response}", algorithm=!{algorithm}, cnonce="!{cnonce}", qop=!{qop}, nc=!{nc}',
                hdr_call_id: m.collect('sip_call_id'),
            })
        },
        {
            event: 'response',
            call_id: oc.id,
            method: 'INVITE',
            msg: sip_msg({
                $rs: '100',
                $rr: 'Trying',
            }),
        },
    ], 1000)

    var expectedResponse = generateDigestResponse({
        username,
        password,
        realm,
        nonce,
        uri,
        method: 'INVITE',
        qop,
        nc: z.$nc,
        cnonce: z.$cnonce,
    })

    if(z.$response != expectedResponse.response) {
        throw new Error(`Incorrect digest response. Expected ${expectedResponse.response} but got ${z.$response}`)
    }

    ic = {
        id: z.$call_id,
        sip_call_id: z.$sip_call_id,
    }

    // now we answer the call
    await sip.call.respond(ic.id, {
        code: 200,
        reason: 'OK',
    })

    // Then we wait for the '200 OK' at the t1 side 
    // We will also get event 'media_update' for both sides indicating media streams (RTP) were set up successfully
    await z.wait([
        {
            event: 'response',
            call_id: oc.id,
            method: 'INVITE',
            msg: sip_msg({
                $rs: '200',
                $rr: 'OK',
            }),
        },
        {
            event: 'media_update',
            call_id: oc.id,
            status: 'ok',
        },
        {
            event: 'media_update',
            call_id: ic.id,
            status: 'ok',
        },
    ], 1000)

    await sip.call.start_inband_dtmf_detection(oc.id)
    await sip.call.start_inband_dtmf_detection(ic.id)

    await sip.call.send_dtmf(oc.id, {digits: '1234', mode: 1})
    await sip.call.send_dtmf(ic.id, {digits: '1234', mode: 1})

    await z.wait([
        {
            event: 'dtmf',
            call_id: ic.id,
            digits: '1234',
            mode: 1,
            media_id: 0,
        },
        {
            event: 'dtmf',
            call_id: oc.id,
            digits: '1234',
            mode: 1,
            media_id: 0,
        },
    ], 2000)

    // now we terminate the call from t1 side
    await sip.call.terminate(oc.id)

    // and wait for termination events
    await z.wait([
        {
            event: 'response',
            call_id: oc.id,
            method: 'BYE',
            msg: sip_msg({
                $rs: '200',
                $rr: 'OK',
            }),
        },
        {
            event: 'call_ended',
            call_id: oc.id,
        },
        {
            event: 'call_ended',
            call_id: ic.id,
        },
    ], 1000)

    console.log("Success")

    await sip.stop()
    process.exit(0)
}


test()
.catch(e => {
    console.error(e)
    process.exit(1)
})

