/* $Id: tonegen_dtmfdet.c 2408 2009-05-02 18:29:00Z mayamatakeshi $ */
/* 
 * Copyright (C) 2008-2009 Teluu Inc. (http://www.teluu.com)
 * Copyright (C) 2003-2008 Benny Prijono <benny@prijono.org>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA 
 */

/**
 * \page page_pjmedia_samples_tonegen_dtmfdet_c Samples: 
 *
 * This is a simple program that connects tonegen with dtmfdest so that DTMF tones generated by tonegen will be detected by dtmfdest 
 * This file is pjsip-apps/src/samples/tonegen_dtmfdet.c
 *
 * \includelineno tonegen_dtmfdet.c
 */


#include <pjmedia.h>
#include <pjlib.h>
#include <pjlib-util.h>
#include <pjlib.h>

#include "util.h"

#include <ctype.h>

#define SAMPLES_PER_FRAME   160 
#define ON_DURATION	    200
#define OFF_DURATION	    50

#define THIS_FILE   "tonegen_dtmfdet.c"

pjmedia_port *tonegen_port;
pjmedia_port *dtmfdet_port;
pjmedia_master_port *master_port;

char g_digits[] = "0123456789abcd*#";

char *g_pending_digits;

static void dtmf_callback(pjmedia_port *port, void *user_data, char digit)
{
	digit = tolower(digit);	
	printf("Digit arrived %c\n", digit);
	if(digit != g_pending_digits[0]) {
		printf("Unexpected digit %c while waiting for %c\n",
			digit,
			g_pending_digits[0]);
		return 1;
	}
	g_pending_digits++;
}

pj_status_t add_dtmf(pjmedia_port *tonegen, char digit){
	pjmedia_tone_digit tone;

	tone.digit = digit; 
	tone.on_msec = ON_DURATION;
	tone.off_msec = OFF_DURATION;
	tone.volume = 0;

	return pjmedia_tonegen_play_digits(tonegen, 1, &tone, 0);
}

pj_status_t set_dtmf_map(pj_pool_t *pool, pjmedia_port *tonegen) {
    /* From http://en.wikipedia.org/wiki/DTMF */
    pjmedia_tone_digit_map *map;
    map = (pjmedia_tone_digit_map*)pj_pool_alloc(pool, sizeof(pjmedia_tone_digit_map));

    map->count = 16;

    map->digits[0].digit = '0';
    map->digits[0].freq1 = 941;
    map->digits[0].freq2 = 1336;

    map->digits[1].digit = '1';
    map->digits[1].freq1 = 697;
    map->digits[1].freq2 = 1209;
 
    map->digits[2].digit = '2';
    map->digits[2].freq1 = 697;
    map->digits[2].freq2 = 1336;
  
    map->digits[3].digit = '3';
    map->digits[3].freq1 = 697;
    map->digits[3].freq2 = 1477;
  
    map->digits[4].digit = '4';
    map->digits[4].freq1 = 770;
    map->digits[4].freq2 = 1209; 
       
    map->digits[5].digit = '5';
    map->digits[5].freq1 = 770;
    map->digits[5].freq2 = 1336;
   
    map->digits[6].digit = '6';
    map->digits[6].freq1 = 770;
    map->digits[6].freq2 = 1477;
   
    map->digits[7].digit = '7';
    map->digits[7].freq1 = 852;
    map->digits[7].freq2 = 1209;
   
    map->digits[8].digit = '8';
    map->digits[8].freq1 = 852;
    map->digits[8].freq2 = 1336;
   
    map->digits[9].digit = '9';
    map->digits[9].freq1 = 852;
    map->digits[9].freq2 = 1477;
   
    map->digits[10].digit = 'a';
    map->digits[10].freq1 = 697;
    map->digits[10].freq2= 1633;
  
    map->digits[11].digit = 'b';
    map->digits[11].freq1 = 770;
    map->digits[11].freq2 = 1633;

    map->digits[12].digit = 'c';
    map->digits[12].freq1 = 852;
    map->digits[12].freq2 = 1633;
 
    map->digits[13].digit = 'd';
    map->digits[13].freq1 = 941;
    map->digits[13].freq2 = 1633;
  
    map->digits[14].digit = '*';
    map->digits[14].freq1 = 941;
    map->digits[14].freq2 = 1209;
  
    map->digits[15].digit = '#';
    map->digits[15].freq1 = 941;
    map->digits[15].freq2 = 1477;

    return pjmedia_tonegen_set_digit_map(tonegen,map);
} 

/*
 * main()
 */
int main()
{
    pj_caching_pool cp;
    pjmedia_endpt *med_endpt;
    pj_pool_t *pool;
    unsigned i;
    pj_status_t status;
    char *pc = g_digits;

    /* Must init PJLIB first: */
    status = pj_init();
    PJ_ASSERT_RETURN(status == PJ_SUCCESS, 1);

    /* Must create a pool factory before we can allocate any memory. */
    pj_caching_pool_init(&cp, &pj_pool_factory_default_policy, 0);

    /* 
     * Initialize media endpoint.
     * This will implicitly initialize PJMEDIA too.
     */
    status = pjmedia_endpt_create(&cp.factory, NULL, 1, &med_endpt);
    PJ_ASSERT_RETURN(status == PJ_SUCCESS, 1);

    /* Create memory pool for our file player */
    pool = pj_pool_create( &cp.factory,	    /* pool factory	    */
			   "app",	    /* pool name.	    */
			   4000,	    /* init size	    */
			   4000,	    /* increment size	    */
			   NULL		    /* callback on error    */
			   );

    status = pjmedia_tonegen_create(pool, 8000, 1, SAMPLES_PER_FRAME, 16, 0, &tonegen_port);
    if (status != PJ_SUCCESS){
	app_perror(THIS_FILE, "Unable to create tonegen",status);
	return 1; 
    }

    status = set_dtmf_map(pool, tonegen_port); 
    if (status != PJ_SUCCESS){
	app_perror(THIS_FILE, "Failed to set digit map", status);
	return 1; 
    }

    
    while(*pc){
	char c = *pc++;
	status = add_dtmf(tonegen_port, c);
	printf("Adding digit %c\n",c);
        if(status != PJ_SUCCESS){
		app_perror(THIS_FILE, "Failed to add dtmf", status);
		return 1;
	}
    }
    g_pending_digits = g_digits;

    status = pjmedia_dtmfdet_create(pool, 
				8000, 
				1,
				SAMPLES_PER_FRAME, 
				16, 
				dtmf_callback,
				0,
				&dtmfdet_port);
    if (status != PJ_SUCCESS){
	app_perror(THIS_FILE, "Unable to create dtmfdet", status);
	return 1; 
    }

    status = pjmedia_master_port_create(pool,
					tonegen_port,
					dtmfdet_port,
					0,
					&master_port);
    if (status != PJ_SUCCESS) {
	app_perror(THIS_FILE, "Unable to create master port", status);
	return 1;
    }

    status = pjmedia_master_port_start(master_port);
    if (status != PJ_SUCCESS) {
	app_perror(THIS_FILE, "Unable to start master port", status);
	return;
    }

    while(*g_pending_digits){
	sleep(1);
    } 
    printf("All expected digits received\n");

    pjmedia_master_port_stop(master_port);

    pjmedia_master_port_destroy(master_port, 1);

    /* Release application pool */
    pj_pool_release( pool );

    /* Destroy media endpoint. */
    pjmedia_endpt_destroy( med_endpt );

    /* Destroy pool factory */
    pj_caching_pool_destroy( &cp );

    /* Shutdown PJLIB */
    pj_shutdown();


    /* Done. */
    return 0;
}
